apiVersion: certs.k8c.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: kubermatic-cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: my-certificate
  namespace: default
spec:
  dnsName: example.k8c.com
  validity: 360d
  secretRef:
    name: my-certificate-secret